import { DEFAULT_SETTINGS, type Bootstrap, type Memory, type Task } from './types.js';
export function demoSeed(): Bootstrap {
  const now = new Date().toISOString();
  const date = now.slice(0, 10);
  const base = { createdAt: now, updatedAt: now, version: 1 };
  const memory = (
    id: string,
    kind: Memory['kind'],
    title: string,
    text: string,
    tags: string[],
    pinned = false,
  ): Memory => ({
    ...base,
    id,
    kind,
    title,
    text,
    tags,
    pinned,
    status: 'active',
    epistemic: 'user_reported',
    entityIds: [],
    taskIds: [],
    sourceRetained: false,
    reviewed: true,
  });
  const task = (id: string, title: string, position: string, extra: Partial<Task> = {}): Task => ({
    id,
    listId: 'personal',
    title,
    position,
    status: 'needsAction',
    notes: '',
    subtasks: [],
    tags: [],
    metadataValid: true,
    ...extra,
  });
  return {
    mode: 'demo',
    settings: { ...DEFAULT_SETTINGS, selectedListIds: ['personal'], name: '' },
    memories: [
      memory(
        'm-focus',
        'goal',
        'Ship the quarterly proposal',
        'Spend less time reacting to email and more time on work that moves the proposal forward. A clear first step each day is what gets me started.',
        ['Work', 'Focus'],
        true,
      ),
      memory(
        'm-health',
        'goal',
        'Run three times a week',
        'Running clears my head. Consistency and enough rest matter more than any single hard session.',
        ['Health'],
        true,
      ),
      memory(
        'm-sam',
        'relationship',
        'Reconnect with Sam',
        'Sam is an old friend. Both of us have been busy. I want to set up a proper catch-up.',
        ['Friendship'],
      ),
      memory(
        'm-avoid',
        'issue',
        'Stalled on the proposal draft',
        'I keep putting off the proposal because the first draft feels too big. Breaking it into a rough outline would make it easier to start.',
        ['Work', 'Blocker'],
      ),
      memory(
        'm-values',
        'preference',
        'Direct feedback, no guilt trips',
        'I want encouragement that leads to a concrete next step. Challenge me, but do not make me feel guilty.',
        ['Coaching'],
      ),
      memory(
        'm-world',
        'preference',
        'Context over headlines',
        'I follow AI, geopolitics and Melbourne news. I want context and reliable sources, not a stream of headlines.',
        ['News'],
      ),
    ],
    tasks: [
      task('t-outline', 'Draft the proposal outline', '0001', {
        due: date,
        tags: ['important'],
        subtasks: [
          {
            id: 's1',
            title: 'Write down the problem it solves',
            done: true,
            createdAt: now,
            createdBy: 'user',
          },
          {
            id: 's2',
            title: 'Sketch three possible approaches',
            done: false,
            createdAt: now,
            createdBy: 'user',
          },
          {
            id: 's3',
            title: 'Pick one to develop first',
            done: false,
            createdAt: now,
            createdBy: 'user',
          },
        ],
      }),
      task('t-review', 'Review this week’s priorities', '0002', { due: date }),
      task('t-sam', 'Message Sam to set up a catch-up', '0003'),
      task('t-run', 'Go for a run', '0004'),
      task('t-book', 'Book the car service', '0005'),
      task('t-read', 'Finish reading the project brief', '0006', { status: 'completed' }),
    ],
    lists: [{ id: 'personal', title: 'My tasks' }],
    proposals: [
      {
        ...base,
        id: 'p-outline',
        title: 'Spend 15 minutes on a rough proposal outline',
        notes: 'First pass only. Do not edit as you go.',
        reason: 'Gets you past the blank page on a stalled task.',
        listId: 'personal',
        status: 'pending',
        sourceId: 'm-avoid',
      },
    ],
    episodes: [],
    jobs: [],
    templates: [
      {
        ...base,
        id: 'mix-morning',
        name: 'Morning focus',
        modules: ['priorities', 'motivation', 'strategy'],
        minutes: 6,
        custom: '',
      },
      {
        ...base,
        id: 'mix-world',
        name: 'World briefing',
        modules: ['news', 'strategy'],
        minutes: 10,
        custom: '',
      },
    ],
    budget: {
      month: date.slice(0, 7),
      spentAud: 0,
      reservedAud: 0,
      limitAud: 20,
      remainingAud: 20,
    },
    connections: {
      google: false,
      anthropic: false,
      gemini: false,
      openai: false,
      news: false,
      push: false,
      cloudSpeech: false,
    },
    taskSyncedAt: now,
  };
}
