import { DEFAULT_SETTINGS, type Bootstrap, type Memory, type Task } from './types.js';
export function demoSeed(): Bootstrap {
  const now = new Date().toISOString();
  const date = now.slice(0, 10);
  const base = { createdAt: now, updatedAt: now, version: 1 };
  const memory = (
    id: string,
    kind: Memory['kind'],
    title: string,
    text: string,
    tags: string[],
    pinned = false,
  ): Memory => ({
    ...base,
    id,
    kind,
    title,
    text,
    tags,
    pinned,
    status: 'active',
    epistemic: 'user_reported',
    entityIds: [],
    taskIds: [],
    sourceRetained: false,
    reviewed: true,
  });
  const task = (id: string, title: string, position: string, extra: Partial<Task> = {}): Task => ({
    id,
    listId: 'personal',
    title,
    position,
    status: 'needsAction',
    notes: '',
    subtasks: [],
    tags: [],
    metadataValid: true,
    ...extra,
  });
  return {
    mode: 'demo',
    settings: { ...DEFAULT_SETTINGS, selectedListIds: ['personal'], name: '' },
    memories: [
      memory(
        'm-focus',
        'goal',
        'Make space for meaningful work',
        'I want to spend less time reacting and more time doing work that moves my long-term goals forward. A clear first step helps me get started.',
        ['Work', 'Focus'],
        true,
      ),
      memory(
        'm-health',
        'goal',
        'Build a rhythm I can sustain',
        'Running helps me clear my head. Consistency and enough rest matter more to me than doing everything perfectly.',
        ['Wellbeing'],
        true,
      ),
      memory(
        'm-sam',
        'relationship',
        'Stay connected with Sam',
        'Sam is an old friend. We have both been busy, and I would like to make time for a proper catch-up.',
        ['Friendship'],
      ),
      memory(
        'm-avoid',
        'issue',
        'Getting started on the proposal',
        'I have been putting off the proposal because the first draft feels too big. Breaking it into a rough outline could make it more approachable.',
        ['Work', 'Starting'],
      ),
      memory(
        'm-values',
        'preference',
        'Direct, thoughtful encouragement',
        'I appreciate encouragement that leads to something practical. I want to be challenged without being made to feel guilty.',
        ['Coaching'],
      ),
      memory(
        'm-world',
        'preference',
        'Keep a wider perspective',
        'I follow AI, geopolitics and local Melbourne news. I want context and reliable sources rather than a stream of headlines.',
        ['News'],
      ),
    ],
    tasks: [
      task('t-outline', 'Write the first outline of the proposal', '0001', {
        due: date,
        tags: ['important'],
        subtasks: [
          {
            id: 's1',
            title: 'Write down the problem we are solving',
            done: true,
            createdAt: now,
            createdBy: 'user',
          },
          {
            id: 's2',
            title: 'Sketch three possible approaches',
            done: false,
            createdAt: now,
            createdBy: 'user',
          },
          {
            id: 's3',
            title: 'Choose one small next step',
            done: false,
            createdAt: now,
            createdBy: 'user',
          },
        ],
      }),
      task('t-review', 'Review this week’s priorities', '0002', { due: date }),
      task('t-sam', 'Message Sam about a catch-up', '0003'),
      task('t-run', 'Head out for an easy run', '0004'),
      task('t-book', 'Book the car service', '0005'),
      task('t-read', 'Finish reading the project brief', '0006', { status: 'completed' }),
    ],
    lists: [{ id: 'personal', title: 'My tasks' }],
    proposals: [
      {
        ...base,
        id: 'p-outline',
        title: 'Spend 15 minutes on a rough proposal outline',
        notes: 'A small first step, without editing as you go.',
        reason: 'A manageable way to get past the blank page.',
        listId: 'personal',
        status: 'pending',
        sourceId: 'm-avoid',
      },
    ],
    episodes: [],
    jobs: [],
    templates: [
      {
        ...base,
        id: 'mix-morning',
        name: 'Morning focus',
        modules: ['priorities', 'motivation', 'strategy'],
        minutes: 6,
        custom: '',
      },
      {
        ...base,
        id: 'mix-world',
        name: 'A wider perspective',
        modules: ['news', 'strategy'],
        minutes: 10,
        custom: '',
      },
    ],
    budget: {
      month: date.slice(0, 7),
      spentAud: 0,
      reservedAud: 0,
      limitAud: 20,
      remainingAud: 20,
    },
    connections: {
      google: false,
      anthropic: false,
      gemini: false,
      openai: false,
      news: false,
      push: false,
      cloudSpeech: false,
    },
    taskSyncedAt: now,
  };
}
